(?)flight ticket list screen
DanilB01/TravelHelper pull request #7
Opened 2024-11-24 21:26 UTC by Seztor

- Сделал 1 часть экрана, где осуществляется выбор локации для билета, дизайна места вылета не было в фигме, мб проглядели, получение данных с data тож сделал
- Для проверки этот экран установлен, как загрузочный вместо MainActivity в InitActivity
- Выбор даты доделаю мб завтра до созвона

2024-11-25 16:46 UTC, Seztor commented
- Добавил фрагменты и переключение с передачей данных
- На layout активити расположены кнопки "далее/назад" для переключения между фрагментами, на layout фрагментов основной ui
- Есть проверка, что все нужные данные введены для перехода между фрагментами

2024-11-27 17:38 UTC, Seztor commented
- добавил экран места вылета 
- пофиксил некоторые баги с отображением текста
- todo(надо будет еще раскидать файлы по нужным папкам)

2024-11-29 16:46 UTC, DanilB01 requested changes

2024-11-29 16:46 UTC, DanilB01 commented on app/build.gradle.kts
> +    implementation(libs.androidx.lifecycle.viewmodel.ktx)
А зачем тебе viewmodel в проекте?

2024-11-29 16:46 UTC, DanilB01 commented on app/src/main/java/ru/itmo/travelhelper/screens/flightTicketsScreen/DataFlightModel.kt
> +open class DataFlightModel: ViewModel() {
А, вот зачем. Данный класс нужен, если мы разрабатываем проект с опорой на архитектуру MVVM. В данном случае, мы используем архитектуру MVP, поэтому использовать viewmodel не нужно. Как и LiveData. Лучше убрать эти библиотеки из gradle.

2024-11-29 16:46 UTC, DanilB01 commented on app/src/main/java/ru/itmo/travelhelper/screens/flightTicketsScreen/FlightArrivalLocationFragment.kt
> +        dataFlightModel.locationDepartureDataMessage.observe(activity as LifecycleOwner, {
Вместо подписки на изменения LiveData, в используемом нами подходе MVP происходит следующее - презентор при помощи интерфейса (View в нашем случае) "руководит" тем, что должно отображаться на экране, в том числе, какие данные отобразить при загрузке экрана. Необходимо немного пересобрать логику отображения данных, основываясь на принципах выбранного архитектурного подхода MVP.

2024-11-29 16:46 UTC, DanilB01 commented on app/src/main/java/ru/itmo/travelhelper/screens/flightTicketsScreen/FlightArrivalLocationFragment.kt
> +
Много пустого пространства, стоит стереть. Также отслеживай, чтобы не было лишних импортов в начале файла.

2024-11-29 16:46 UTC, DanilB01 commented on app/src/main/java/ru/itmo/travelhelper/screens/flightTicketsScreen/FlightArrivalLocationFragment.kt
> +
аналогично про пустое место

2024-11-29 16:46 UTC, DanilB01 commented on app/src/main/java/ru/itmo/travelhelper/screens/flightTicketsScreen/UpdateListInterface.kt
> +interface UpdateListInterface {
После исключения использования LiveData стоит убрать этот интерфейс

2024-11-29 16:46 UTC, DanilB01 commented on app/src/main/java/ru/itmo/travelhelper/screens/flightTicketsScreen/FlightArrivalLocationFragment.kt
> +
Стоит отследить форматирование кода и в других местах (убрать такие отступы в других классах - все это нужно для лучшей читаемости кода).

2024-11-29 16:52 UTC, DanilB01 commented on domain/src/main/java/ru/itmo/domain/models/flightTicketListModels/LocationModel.kt
> +data class CountryModel(
Лучше выносить data class'ы в отдельный файл, чтобы один файл .kt соответствовал одному дата классу - то есть в данном случае будет три отдельных файла для разных дата классов.

2024-11-29 16:53 UTC, DanilB01 commented
А еще, общее замечание - по названиям пакетов в проекте. Стоит выбрать одно краткое и звучное название, которое полностью опишет лежащие внутри файлы, причем без повторения родительского названия. Например, в папке репозиториев (repository) следует сделать подпапку airport/fly/etc... (название на выбор), которая будет отвечать за все, что связано с выбором билетов на самолет. Не нужно дублировать название (использовать airport вместо airportRepository и тд.). Аналогично с юзкейсами.

2024-11-29 17:09 UTC, Seztor commented on app/src/main/java/ru/itmo/travelhelper/screens/flightTicketsScreen/UpdateListInterface.kt
> +interface UpdateListInterface {
Этот интерфейс же связан просто с реализацией выпадающего списка, как он с live data связан

2024-11-29 17:15 UTC, DanilB01 commented on app/src/main/java/ru/itmo/travelhelper/screens/flightTicketsScreen/UpdateListInterface.kt
> +interface UpdateListInterface {
при обновлении элементов списка следует обращаться к презентору за обновлением данных списка, после презентор выполняет обработку данных и выдает новый список, который передает активити через его интерфейс.

2024-11-29 17:15 UTC, DanilB01 commented on app/src/main/java/ru/itmo/travelhelper/screens/flightTicketsScreen/UpdateListInterface.kt
> +interface UpdateListInterface {
тут не livedata, согласен, проглядел

2024-12-02 14:04 UTC, DanilB01 commented on domain/src/main/java/ru/itmo/domain/usecases/flightTicketListUseCases/GetLocationUseCase.kt
> +class GetLocationUseCase(private val locationRepository: LocationRepository) {
UseCase - это единица бизнес-логики. То есть, загрузка стран, загрузка городов, загрузка аэропортов - все это является тремя разными единицами бизнес-логики, которые участвуют в одном процессе - выбор места вылета\прилета. У юзкейса должен быть один метод - execute, который выполняет эту самую единицу бизнес-логики.
То есть, юзкейс - это единица бизнес-логики, а за бизнес-процессы отвечают презенторы экранов - что и как отобразить на экране, где взять, и тд. 
Таким образом, следует немного изменить реализацию бизнес-логики и вместо этого юзкейса завести три юзкейса, каждый из которых будет отвечать за загрузку тех или иных данных и иметь только единственный метод - execute.

2024-12-02 14:14 UTC, DanilB01 commented on app/src/main/java/ru/itmo/travelhelper/screens/flightScreens/FlightDepartureFragment.kt
> +    interface OnItemClickListener {
Лучше подобные интерфейсы, а также адаптеры списков выносить в отдельные .kt файлы - так удобнее их искать и видеть структуру проекта, в частности, какие классы есть и используются в проекте.

2024-12-02 14:19 UTC, DanilB01 commented
Несколько общих замечаний:
- Достаточно много лишних пустых строк - следует проверить во всех файлах и убрать лишние пропуски строк.
- Если код какого-то метода или функции получается объемным (условно, метод\функцию необходимо скроллить), то хорошей практикой является разбиение кода на приватные подфункции и называть выделенные подфункции в соответствии с тем, что делает данная подфункция. В таком случае, основной метод может содержать серию вызовов приватных методов, а по названию этих подметодов будет понятно, что делается в рамках выполнения данного кода.
- По поводу названий, напомню, что не обязательно дублировать название папки в названии подпапки (например, презенторы или репозитории). Также, название класса должно оканчиваться названием структурного элемента - будь то активити, презентор или юзкейс, репозиторий (FlightPresenter вместо FlightPresenterActivity, FlightArrivalPresnter вместо FlightPresnterArrivalFragment и тд.), иначе может возникнуть путаница - почему активити находится в папке презенторов и тд, то есть, это ускоряет навигацию по структуре проекта.

2024-12-08 18:36 UTC, DanilB01 commented on app/src/main/java/ru/itmo/travelhelper/presenter/flight/FlightTicketsReturnPresenter.kt
> +class FlightTicketsReturnPresenter(private val view: FlightTicketsReturnFragment) {
Согласно принципам архитектуры MVP,  презентору должен передаваться интерфейс, а не конкретный экран.. То есть, тип параметра view должен быть FlightDepartureView, который реализует данный фрагмент. Справедливо и для других презенторов.

2024-12-08 18:36 UTC, DanilB01 commented on app/src/main/java/ru/itmo/travelhelper/screens/InitActivity.kt
> +            val intentMainActivity = Intent(this, FlightActivity::class.java)
Перед слиянием в ветку develop не забудь вернуть логику отображения как оно есть на самом деле (переход на Main активити вместо Flight)

2024-12-08 18:36 UTC, DanilB01 commented on app/src/main/java/ru/itmo/travelhelper/screens/flight/FlightActivity.kt
> +        // 4 - Tickets Return Screen
Пока можно оставить так, но на будущее - лучше использовать enum классы.

2024-12-08 18:36 UTC, DanilB01 commented on app/src/main/java/ru/itmo/travelhelper/view/flight/FlightActivityView.kt
> +}
Если интерфейс нужен согласно архитектуре MVP, но у него нет методов и переменных - можно оставить просто название интерфейса без фигурных скобок. Справедливо и для других интерфейсов View

2024-12-08 18:36 UTC, DanilB01 commented on domain/src/main/java/ru/itmo/domain/models/flight/AirportModel.kt
> +data class AirportModel(
Модели потом расширятся с учетом данных с API, но сейчас лучше добавить для них модели и мапперы. Погляди пример с отелями - HotelApiModel и HotelMapper. Первый дата класс отвечает за вид моедели данных, какие они будут приходить с сервера, а маппер преобразовывает модели данных с сервера в доменные модели, чтобы приложение дальше удачно работало с доменными моделями. Лучше делать так, т.к. модели данных, которые приходят с сервера, могут поменяться, и если мы ожидаем сразу доменные модели данных с сервера, то все может сломаться и придется переписывать много кода, который использует эти доменные модели. Таким образом, лучше делать эти промежуточные апишные модели данных. Добавь такое для аэропортов, городов и стран, а также мапперы для этих трех сущностей. Плюс, стоит учесть, что в репозитории получаются сетевые модели данных, которые потом при помощи мапперов должны преобразовываться в доменные (см. HotelRepositoryImpl).

2024-12-09 13:04 UTC, merged